const DEFAULT_SEARCH_LOCATION = { lat: 23.804093, lng: 90.4152376 }
const DEFAULT_SEARCH_CATEGORY = ['Any']
const DEFAULT_SEARCH_PRICE_RANGE = [0, 20202]
const DEFAULT_MAX_PROPERTY_SEARCH_DISTANCE = 50000

export {
	DEFAULT_SEARCH_CATEGORY,
	DEFAULT_SEARCH_LOCATION,
	DEFAULT_SEARCH_PRICE_RANGE,
	DEFAULT_MAX_PROPERTY_SEARCH_DISTANCE,
}
